language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python -m unittest src.CalculatorTests

branches:
  only:
    - master
after_success:
  coveralls